### ISSUE TITLE
No dashboard information

### ISSUE THREAD

**Issue by scottkellie** [Mbarmem/Grafana.Dashboard#1]
Following through this and the link for the Grafana dashboard info is not live and nothing in the readme.

**Comment by aman207** [comment]
Looks like this is the dashboard: https://grafana.com/grafana/dashboards/12966
Found it here: https://www.reddit.com/r/homelab/comments/inr3ku/finally_got_a_dashboard_after_months_of_tweaking/

The creator doesn't like to reuse usernames, makes is really hard to find stuff
